version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "System.Text.Json"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - "*"
