name: Check Markdown

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - .github/workflows/check-markdown.yml
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: bmazzarol/bmazzarol/.github/actions/check-markdown@main
        with:
          targetMdFiles: |
            "HttpBuildR*/**/*.md" "*.md" "!LICENSE.md"